imagePullSecrets:

logic:
  replicaCount: 1
  service: 
    type: ClusterIP
    type: LoadBalancer
    logicport: 8050
    persistport: 8051
  image:
    # e.g., docker.pkg.github.com/maana-io/physical-quantity-deployment/maana-physical-quantity-logic
    repository: <my-pkg-repo>
    pullPolicy: IfNotPresent
  version:  


podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ckg: {}
  # url

auth: {}
  # provider
  # audience
  # identifier
  # client-identifier
  # domain
  # secret


