apiVersion: v1
kind: Service
metadata:
  name: {{ include "<my-service>.fullname" . }}-logic
  labels:
    {{- include "<my-service>.labels" . | nindent 4 }}
spec:
  type: {{ .Values.logic.service.type }}
  ports:
    - port: {{ .Values.logic.service.logicport }}
      targetPort: <my-service>-logic
      protocol: TCP
      name: <my-service>-logic
  selector:
    {{- include "<my-service>.selectorLabels" . | nindent 4 }}
    app: {{ include "<my-service>.fullname" . }}-logic

